CREATE TABLE member (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY,
    social_id       VARCHAR(255) NOT NULL,
    nickname        VARCHAR(255) NOT NULL,
    email           VARCHAR(255) NOT NULL,
    profile_image   VARCHAR(255),
    role            VARCHAR(255) NOT NULL CHECK (role IN ('ROLE_MEMBER', 'ROLE_ADMIN', 'ROLE_OWNER')),
    social_provider VARCHAR(255) NOT NULL CHECK (social_provider IN ('KAKAO', 'GOOGLE')),
    created_at      TIMESTAMP(6),
    updated_at      TIMESTAMP(6),
    CONSTRAINT pk_member PRIMARY KEY (id),
    CONSTRAINT uk_member_social_login UNIQUE (social_provider, social_id)
);

CREATE TABLE drink (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(255) NOT NULL,
    abv           FLOAT(53)    NOT NULL,
    sweetness     INTEGER      NOT NULL,
    bitterness    INTEGER      NOT NULL,
    carbonation   INTEGER      NOT NULL,
    richness      INTEGER      NOT NULL,
    acidity       INTEGER      NOT NULL,
    non_alcoholic BOOLEAN      NOT NULL,
    CONSTRAINT pk_drink PRIMARY KEY (id)
);

CREATE TABLE anju (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    sweetness   INTEGER      NOT NULL,
    bitterness  INTEGER      NOT NULL,
    carbonation INTEGER      NOT NULL,
    richness    INTEGER      NOT NULL,
    acidity     INTEGER      NOT NULL,
    CONSTRAINT pk_anju PRIMARY KEY (id),
    CONSTRAINT uk_anju_name UNIQUE (name)
);

CREATE TABLE anju_allergy_type (
    anju_id      BIGINT       NOT NULL,
    allergy_type VARCHAR(255) NOT NULL CHECK (allergy_type IN (
        'EGG', 'MILK', 'PEANUT', 'WALNUT', 'PINE_NUT', 'SHELLFISH', 'SHRIMP', 'CRAB', 'SQUID', 'MACKEREL',
        'PORK', 'BEEF', 'CHICKEN', 'SOYBEAN', 'WHEAT', 'BUCKWHEAT', 'PEACH', 'TOMATO', 'SULFITE')),
    CONSTRAINT pk_anju_allergy_type PRIMARY KEY (anju_id, allergy_type),
    CONSTRAINT fk_anju_allergy_type_anju FOREIGN KEY (anju_id) REFERENCES anju (id)
);

CREATE TABLE music_mood (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    title         VARCHAR(255) NOT NULL,
    formality     INTEGER      NOT NULL,
    romance       INTEGER      NOT NULL,
    celebration   INTEGER      NOT NULL,
    comfort       INTEGER      NOT NULL,
    streaming_url VARCHAR(255) NOT NULL,
    CONSTRAINT pk_music_mood PRIMARY KEY (id),
    CONSTRAINT uk_music_mood_title UNIQUE (title)
);

-- member_id는 도메인 간 참조라 FK를 걸지 않는다.
CREATE TABLE pairing_feedback (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id         BIGINT       NOT NULL,
    drink_id          BIGINT       NOT NULL,
    anju_id           BIGINT       NOT NULL,
    music_mood_id     BIGINT       NOT NULL,
    relationship_type VARCHAR(255) NOT NULL CHECK (relationship_type IN ('BOSS', 'FRIEND', 'COLLEAGUE', 'LOVER')),
    mood_type         VARCHAR(255) NOT NULL CHECK (mood_type IN ('FORMAL', 'CASUAL', 'ROMANTIC', 'CELEBRATORY')),
    rating            VARCHAR(255) NOT NULL CHECK (rating IN ('LIKE', 'DISLIKE')),
    created_at        TIMESTAMP(6),
    updated_at        TIMESTAMP(6),
    CONSTRAINT pk_pairing_feedback PRIMARY KEY (id),
    CONSTRAINT fk_pairing_feedback_drink FOREIGN KEY (drink_id) REFERENCES drink (id),
    CONSTRAINT fk_pairing_feedback_anju FOREIGN KEY (anju_id) REFERENCES anju (id),
    CONSTRAINT fk_pairing_feedback_music_mood FOREIGN KEY (music_mood_id) REFERENCES music_mood (id)
);
