CREATE TABLE drink_style (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    category    VARCHAR(255) NOT NULL,
    sweetness   INTEGER      NOT NULL,
    bitterness  INTEGER      NOT NULL,
    carbonation INTEGER      NOT NULL,
    richness    INTEGER      NOT NULL,
    acidity     INTEGER      NOT NULL,
    CONSTRAINT pk_drink_style PRIMARY KEY (id),
    -- 값이 늘어날 때 후속 마이그레이션이 DROP 후 다시 ADD할 수 있도록 check 제약에 이름을 붙인다.
    CONSTRAINT ck_drink_style_category CHECK (category IN (
        'BEER', 'WINE', 'SOJU', 'MAKGEOLLI', 'WHISKY', 'HIGHBALL', 'NON_ALCOHOLIC')),
    CONSTRAINT uk_drink_style_name UNIQUE (name)
);

INSERT INTO drink_style (id, name, category, sweetness, bitterness, carbonation, richness, acidity) VALUES
    (1, '희석식 소주', 'SOJU', 2, 2, 0, 1, 1),
    (2, '라거', 'BEER', 1, 3, 4, 1, 2),
    (3, '생막걸리', 'MAKGEOLLI', 3, 1, 2, 2, 3),
    (4, '레드 와인', 'WINE', 2, 2, 0, 3, 4),
    (5, '스카치 위스키', 'WHISKY', 1, 4, 0, 4, 1),
    (6, '위스키 하이볼', 'HIGHBALL', 2, 2, 4, 1, 2),
    (7, '무알코올 모히또', 'NON_ALCOHOLIC', 3, 1, 4, 1, 4),
    (8, '무알코올 하이볼', 'NON_ALCOHOLIC', 2, 2, 4, 1, 2);

-- id를 명시해 넣으면 IDENTITY 시퀀스가 전진하지 않으므로, 다음 INSERT가 시드 id와 충돌하지 않게 최댓값으로 맞춘다.
SELECT setval(pg_get_serial_sequence('drink_style', 'id'), (SELECT MAX(id) FROM drink_style));

-- 기존 행을 채운 뒤에 NOT NULL을 걸어야 행이 있는 DB에서도 컬럼 추가가 실패하지 않는다.
ALTER TABLE drink
    ADD COLUMN drink_style_id BIGINT,
    ADD COLUMN source         VARCHAR(255),
    ADD COLUMN external_id    VARCHAR(255);

UPDATE drink
SET drink_style_id = seed.drink_style_id,
    source         = 'SEED',
    external_id    = seed.external_id
FROM (VALUES
    (1, 1, 'soju'),
    (2, 2, 'beer'),
    (3, 3, 'makgeolli'),
    (4, 4, 'red-wine'),
    (5, 5, 'whisky'),
    (6, 6, 'highball'),
    (7, 7, 'virgin-mojito'),
    (8, 8, 'non-alcoholic-highball')
) AS seed (drink_id, drink_style_id, external_id)
WHERE drink.id = seed.drink_id;

ALTER TABLE drink
    ALTER COLUMN drink_style_id SET NOT NULL,
    ALTER COLUMN source SET NOT NULL,
    ALTER COLUMN external_id SET NOT NULL,
    ADD CONSTRAINT ck_drink_source CHECK (source IN ('SEED')),
    ADD CONSTRAINT fk_drink_drink_style FOREIGN KEY (drink_style_id) REFERENCES drink_style (id),
    ADD CONSTRAINT uk_drink_source_external_id UNIQUE (source, external_id);
